### ISSUE TITLE
Get linux working on virtualbox

### ISSUE THREAD

**Issue by jpsider** [BelayTechnologies/SummitRTS#85]
Just never tried it! Need to build a vm, then test.

**Comment by esabelhaus** [comment]
Want me to tackle this?

**Comment by esabelhaus** [comment]
also, do we want GUI or non GUI?

**Comment by jpsider** [comment]
Everything is run via cmdline, so GUI is not needed. However I do have it installed. and I have it working! so I will be closing this one out.

**Comment by jpsider** [comment]
Ticket resolved. New ticket added to track bug with revert snapshot..  might need to add a wait..?
